# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ehubmobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ehubmobile
  pod 'AppCenter/Crashes', '~> 1.3.0'
  pod 'AppCenter/Analytics', '~> 1.3.0'
  pod 'AppCenterReactNativeShared', '~> 1.2.0'

  

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'ehubmobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ehubmobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ehubmobile-tvOS

  target 'ehubmobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
